apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-blob-storage-fuse
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azureblob-fuse-premium
  resources:
    requests:
      storage: 2Gi
