apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-blob-storage-nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azureblob-nfs-premium
  resources:
    requests:
      storage: 2Gi
